[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  # Supabase Configuration - Replace with your actual values
  NEXT_PUBLIC_SUPABASE_URL = "https://your-project-ref.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-public-anon-key"

# Redirect rules for Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"